### ISSUE TITLE
Error when trying to install (nodejs 4.2.1, npm 3.3.8)

### ISSUE THREAD

**Issue by doberkofler** [Medium/phantomjs#399] opened 2015-10-21 07:16 UTC
When trying to install phantomjs on Windows using node 4.2.1 and npm 3.3.8, I get the following error message:

```
D:\MyDev\ljs_app\trunk\periscope\build>npm install phantomjs

> phantomjs@1.9.18 install D:\MyDev\ljs_app\trunk\periscope\build\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
  [=======================================-] 96% 0.0s
Received 7292K total.
Extracting zip contents
Removing D:\MyDev\ljs_app\trunk\periscope\build\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1445411603046\phantomjs-1.9.8-windows -> D:\MyDev\ljs_app\trunk\periscope\build\n
ode_modules\phantomjs\lib\phantom
Phantom installation failed { [Error: EBUSY: resource busy or locked, open 'C:\temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1445411603046\phantomjs-1.9.8-
windows\phantomjs.exe']
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\temp\\phantomjs\\phantomjs-1.9.8-windows.zip-extract-1445411603046\\phantomjs-1.9.8-windows\\phantomjs.exe' } Error: EBUSY: resource busy or locked
, open 'C:\temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1445411603046\phantomjs-1.9.8-windows\phantomjs.exe'
    at Error (native)
```

**Comment by JohnTheBeloved** [comment] 2015-10-22 11:20
Please, I am getting something Similar


Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Using proxy http://127.0.0.1:3128/
Receiving...

Error making request.
Error: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.onError (/home/johnthebeloved/development/project/nodejs/smartinsure/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:174:17)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketOnData (_http_client.js:322:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "node" "/home/johnthebeloved/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/johnthebeloved/development/project/nodejs/smartinsure/npm-debug.log

**Comment by nuxdie** [comment] 2015-10-22 13:12
me too:
````
> phantomjs@1.9.18 install /Users/a.tsatsin/pro/lj/htdocs/js/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/pj/m6x5f1xs31b56yg2wggp9qzw0000gp/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN EPACKAGEJSON js@1.0.0 No description
npm WARN EPACKAGEJSON js@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a.tsatsin/pro/lj/htdocs/js/npm-debug.log

**Comment by okket** [comment] 2015-10-22 13:35
For the record, it fails with npm 2.14.7 too (node 4.2.1 / OS X 10.11.1):

```
> phantomjs@1.9.18 install /Users/okketimm/.nvm/versions/node/v4.2.1/lib/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/yc/k5rvjw555kn8x_g72v1dlx6h0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...

Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/okketimm/.nvm/versions/node/v4.2.1/bin/node" "/Users/okketimm/.nvm/versions/node/v4.2.1/bin/npm" "-g" "install" "phantomjs"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/okketimm/npm-debug.log
```

**Comment by SakyaStelios** [comment] 2015-12-10 16:15
I get an unklink error:

> phantomjs@1.9.19 install D:\Kurylenko\node_modules\phantomjs
> node install.js

Looks like an `npm install -g` on windows; unable to check for already installed
 version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-wind
ows.zip
Saving to C:\Users\GIANCA~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows
.zip
Using proxy http://10.10.8.230:3128/
Receiving...
  [=======================================-] 98% 0.0s
Received 7292K total.
Extracting zip contents
Removing D:\Kurylenko\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\GIANCA~1\AppData\Local\Temp\phantomjs\phantomj
s-1.9.8-windows.zip-extract-1449763962661\phantomjs-1.9.8-windows -> D:\Kurylenk
o\node_modules\phantomjs\lib\phantom
Phantom installation failed { [Error: EPERM: operation not permitted, unlink 'C:
\Users\GIANCA~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract
-1449763962661\phantomjs-1.9.8-windows\phantomjs.exe']
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\GIANCA~1\\AppData\\Local\\Temp\\phantomjs\\phantomjs-1.9.8-w
indows.zip-extract-1449763962661\\phantomjs-1.9.8-windows\\phantomjs.exe' } Erro
r: EPERM: operation not permitted, unlink 'C:\Users\GIANCA~1\AppData\Local\Temp\
phantomjs\phantomjs-1.9.8-windows.zip-extract-1449763962661\phantomjs-1.9.8-wind
ows\phantomjs.exe'
    at Error (native)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.6
npm WARN kurylenko@1.1.1 No repository field.
npm WARN kurylenko@1.1.1 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Giancarlo\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Kurylenko\npm-debug.log

**Comment by osukaa** [comment] 2015-12-15 03:34
I get a similar error

```
\
Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie, Accept-Encoding",
  "cache-control": "max-age=900",
  "content-type": "text/html; charset=utf-8",
  "strict-transport-security": "max-age=31536000",
  "date": "Tue, 15 Dec 2015 03:29:55 GMT",
  "x-served-by": "app12",
  "content-language": "en",
  "accept-ranges": "bytes",
  "x-static-version": "3ee6c8278d42",
  "etag": "\"5269d89a1ab13b38c5e23d31c035666f\"",
  "x-render-time": "0.0151700973511",
  "x-version": "3ee6c8278d42",
  "x-request-count": "8",
  "x-frame-options": "SAMEORIGIN",
  "content-length": "7704",
  "connection": "close",
  "x-cache-info": "cached"
}
Make sure your network and proxy settings are correct.
```

**Comment by muhasturk** [comment] 2016-01-25 23:29
yes same here

```
> phantomjs@2.1.2 install /Users/muhasturk/Yandex.Disk/Docs/Project/personal-site/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/27/7vhsw2js4q18_2j72qm2y1nm0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error requesting archive.
Status: 429
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/3.5.3 node/v5.5.0 darwin x64"
  },
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie",
  "cache-control": "max-age=900",
  "content-type": "text/plain",
  "strict-transport-security": "max-age=31536000",
  "date": "Mon, 25 Jan 2016 23:26:12 GMT",
  "x-served-by": "app-106",
  "expires": "Mon, 25 Jan 2016 23:26:12 GMT",
  "content-language": "en",
  "etag": "\"62dcd5481fd29816ecc5ae00be2da0b0\"",
  "x-static-version": "74f625e07ed8",
  "x-render-time": "0.0095579624176",
  "connection": "close",
  "x-request-count": "72",
  "x-frame-options": "SAMEORIGIN",
  "last-modified": "Mon, 25 Jan 2016 23:26:12 GMT",
  "x-version": "74f625e07ed8",
  "content-length": "46"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
mattia-astorino-portfolio@1.0.0 /Users/muhasturk/Yandex.Disk/Docs/Project/personal-site
└─┬ browser-sync@2.11.1
  ├─┬ chokidar@1.4.1
  │ └─┬ fsevents@1.0.6
  │   └─┬ node-pre-gyp@0.6.17
  │     └─┬ request@2.67.0
  │       └─┬ http-signature@1.1.0
  │         └── assert-plus@0.1.5
  ├─┬ fs-extra@0.26.4
  │ ├── jsonfile@2.2.3
  │ └── rimraf@2.5.1
  └─┬ localtunnel@1.8.1
    └─┬ request@2.65.0
      └─┬ http-signature@0.11.0
        ├── asn1@0.1.11
        ├── assert-plus@0.1.5
        └── ctype@0.5.3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@2.1.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.1.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/muhasturk/Yandex.Disk/Docs/Project/personal-site/npm-debug.log
```

**Comment by ankr** [comment] 2016-02-24 17:02
Any news on this half year old issue?

**Comment by nicks** [comment] 2016-02-24 17:21
i'm closing this, as it's become a dumping ground for unreproducible, unrelated issues. I think all can be resolved by the FAQ
https://github.com/Medium/phantomjs#troubleshooting

**Closed by nicks** 2016-02-24 17:21 UTC
